# Generated by Django 2.1 on 2018-11-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='组件名')),
                ('deploy_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='发布单号')),
                ('env_name', models.CharField(blank=True, max_length=24, null=True, verbose_name='环境')),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='IP地址')),
                ('log_content', models.CharField(blank=True, max_length=4096, null=True, verbose_name='日志内容')),
                ('operation_no', models.IntegerField(blank=True, default=0, null=True, verbose_name='操作批次')),
                ('operation_type', models.CharField(blank=True, max_length=24, null=True, verbose_name='操作类型')),
                ('user_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='用户名')),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-change_date',),
            },
        ),
    ]
