# Generated by Django 2.1 on 2018-10-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wslog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logsdb',
            old_name='env_type',
            new_name='env_name',
        ),
    ]
